name: Build release

on: 
  workflow_dispatch:
    inputs:
      tag:
        required: True
  push:
    tags:  # Tags need to be annotated with git tag 1.x.x -a; push tags with git push origin 1.x.x, or use follow tags = true in git config file.
    - '*'
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Move mod files
      run: |
        mkdir minai
        mv *.esp minai
        mv *.ini minai
        mv Scripts minai
        mv Data minai
        mv minai_plugin minai/
        mkdir minai/mantella_files
        mv config.ini minai/mantella_files
        mv prompts_vanilla.txt minai/mantella_files
        
    - name: Zip the files
      uses: TheDoctor0/zip-release@0.7.6
      with:
        path: "./minai/*"
        type: "zip"
        filename: "MinAI-${{github.ref_name}}:.zip"

    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "MinAI-${{github.ref_name}}:.zip"
        token: ${{ secrets.RELEASE_TOKEN }}
        generateReleaseNotes: true
        prerelease: true  # Remember to set release status manually
